# Generated by Django 4.1.6 on 2024-06-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_uploaded_in', models.CharField(blank=True, max_length=255, null=True)),
                ('empty_field_a', models.CharField(blank=True, max_length=255, null=True)),
                ('empty_field_b', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=2500)),
                ('empty_field_a', models.CharField(blank=True, max_length=255, null=True)),
                ('empty_field_b', models.CharField(blank=True, max_length=255, null=True)),
                ('empty_field_c', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
