# Generated by Django 4.1.6 on 2024-06-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('parties_concerned', models.CharField(max_length=1500)),
                ('empty_field_a', models.CharField(blank=True, max_length=255, null=True)),
                ('empty_field_b', models.CharField(blank=True, max_length=255, null=True)),
                ('empty_field_c', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
