# Generated by Django 4.1.6 on 2024-06-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
