# Generated by Django 4.1.6 on 2024-06-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_file_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimesnsion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('empty_field_a', models.CharField(blank=True, max_length=255, null=True)),
                ('empty_field_b', models.CharField(blank=True, max_length=255, null=True)),
                ('empty_field_c', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=1500)),
                ('department', models.CharField(max_length=100)),
                ('empty_field_a', models.CharField(blank=True, max_length=255, null=True)),
                ('empty_field_b', models.CharField(blank=True, max_length=255, null=True)),
                ('empty_field_c', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
