# Generated by Django 4.1.6 on 2024-06-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dimesnsion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimesnsion',
            name='row_attribute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
