# Generated by Django 4.1.6 on 2024-06-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dimesnsion_row_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='file_name',
            field=models.CharField(default=None, max_length=2500),
            preserve_default=False,
        ),
    ]
